config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'countries#index'

	resources :countries, param: :slug, path: '', only: [:index, :show] do
		collection do
			get 'refresh'
		end

		resources :leagues, param: :slug, path: '', only: [:index, :show] do
			collection do
				get 'refresh'
			end

			resources :seasons, param: :slug, path: '', only: [:index, :show] do
				collection do
					get 'refresh'
				end

				resources :fixtures, param: :slug, only: [:index, :show] do
					collection do
						get 'refresh'
					end
				end
			end

			resources :teams, only: [:index, :show] do
				collection do
					get 'refresh'
				end
			end
		end
	end

	#
	#resources :leagues, only: [:index, :show] do
	#	collection do
	#		get 'refresh'
	#	end
	#end

	resources :venues, param: :slug, only: [:index, :show] do
	  collection do
	    get 'refresh'
    end
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
end

app/models/season.rb
class Season < ApplicationRecord
	include Sluggable

	belongs_to :league
	has_many :fixtures, dependent: :destroy
	has_many :teams, through: :fixtures
	has_many :players, through: :teams

	def self.fetch_and_update_from_api(league)
		api_client = ApiClient.new
		remote_seasons = api_client.fetch('leagues', seasons)

		remote_seasons.each do |remote_season|
			create_or_update(remote_season)
		end
	end

	def self.find_or_initialize_and_update(league, season_year)
		season_data = league.seasons.find_or_initialize_by(year: season_year)

		if season_data.new_record?
			Rails.logger.info "Creating new season: #{season_data['year']}"
			# puts "Creating new season: #{season_data['year']}"
			season_data.assign_attributes(
				start_date: season_data['start'],
				end_date: season_data['end'],
				current: season_data['current'],
				coverage: season_data['coverage']
			)
			season_data.generate_slug
		else
			Rails.logger.info "Updating season: #{season_data['year']}"
			# puts "Updating season: #{season_data['year']}"
			season_data.assign_attributes(
				coverage: season_data['coverage']
			)
		end
		season_data.save!
		season_data
	end
end

app/controllers/seasons_controller.rb
class SeasonsController < ApplicationController
	before_action :set_league, only: [:index, :show, :refresh]

  def index
		@seasons = @league.seasons

		puts @seasons
  end

  def show
  	@season = @league.seasons.find(params[:id])
  end

  def refresh

  end

	private

	def set_league

		@league = League.find_by!(slug: params[:league_slug])
	end
end

app/helpers/seasons_helper.rb
module SeasonsHelper
end

app/views/seasons/_seasons_list.html.erb
<table class="table">
	<thead>
		<tr>
			<th scope="col" class="text-nowrap">Year</th>
			<th scope="col">Current</th>
			<th scope="col">Coverage</th>
		</tr>
	</thead>
	<tbody>
		<% seasons.each do |season| %>
			<tr class="season">
				<th scope="row" class="text-nowrap"><%= link_to "#{season.start_date.year} - #{season.end_date.year}", country_league_season_fixtures_path(@league.country.slug, @league.slug, season.slug) %></th>
				<td><%= season.current %></td>
				<td><%= season.coverage.to_json %></td>
			</tr>
		<% end %>
	</tbody>
</table>

app/views/seasons/index.html.erb
<%= render partial: 'seasons/seasons_list', locals: { seasons: @league.seasons.order(year: :desc) } %>

app/views/seasons/refresh.html.erb
<h1>Seasons#refresh</h1>
<p>Find me in app/views/seasons/refresh.html.erb</p>

app/views/seasons/show.html.erb
<h1>Seasons#show</h1>
<p>Find me in app/views/seasons/show.html.erb</p>