config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'countries#index'

	resources :countries, param: :slug, path: '', only: [:index, :show] do
		collection do
			get 'refresh'
		end

		resources :leagues, param: :slug, path: '', only: [:index, :show] do
			collection do
				get 'refresh'
			end

			resources :seasons, param: :slug, path: '', only: [:index, :show] do
				collection do
					get 'refresh'
				end

				resources :fixtures, param: :slug, only: [:index, :show] do
					collection do
						get 'refresh'
					end
				end
			end

			resources :teams, only: [:index, :show] do
				collection do
					get 'refresh'
				end
			end
		end
	end

	#
	#resources :leagues, only: [:index, :show] do
	#	collection do
	#		get 'refresh'
	#	end
	#end

	resources :venues, param: :slug, only: [:index, :show] do
	  collection do
	    get 'refresh'
    end
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
end

app/models/league.rb
class League < ApplicationRecord
	include Sluggable

	belongs_to :country
	has_many :seasons, dependent: :destroy
	has_many :teams
	has_many :fixtures

	def self.fetch_and_update_from_api(country = nil)
		api_client = ApiClient.new
		remote_leagues = api_client.fetch('leagues')

		remote_leagues.each do |remote_league|

			league_data = remote_league['league']
			country_data = remote_league['country']
			seasons_data = remote_league['seasons']

			country = Country.create_or_update(country_data)
			league = League.create_or_update(league_data, country)

			seasons_data.each do |season_data|
				Season.find_or_initialize_and_update(league, season_data['year'])
			end
		end
	end

	def self.find_or_initialize_and_update(league_data, country)
		league = country.leagues.find_or_initialize_by(id: league_data['id'])

		puts "League: #{league.inspect}"
		puts "League country: #{country.inspect}"

		if league.new_record?
			Rails.logger.info "Creating new league: #{league_data['name']}"
			# puts "Creating new league: #{league_data['name']}"
			league.assign_attributes(
				name: league_data['name'],
				league_type: league_data['type'],
				logo: league_data['logo'],
				country: country
			)
			league.slug ||= league.name.parameterize
 		else
			Rails.logger.info "Updating league: #{league_data['name']}"
			#	puts "Updating league: #{league_data['name']}"
			league.assign_attributes(
				name: league_data['name'],
				logo: league_data['logo']
			)
		end

		league.save!
		# puts "League saved: #{league.id} - #{league.name}"
		league
	end
end

app/controllers/leagues_controller.rb
class LeaguesController < ApplicationController
	before_action :set_country, only: [:index, :show, :refresh]

  def index
		@leagues = @country ? @country.leagues : League.all
  end

  def show
		@league = @country.leagues.find_by!(slug: params[:slug])
  end

	def refresh

		League.fetch_and_update_from_api(@country)
		@leagues = @country ? @country.leagues : League.all

		respond_to do |format|
			format.html {
				if @country
					redirect_to country_leagues_path(@country.slug),
					notice: 'Leagues udpated sucessfully'
				else
					redirect_to leagues_path,
					notice: 'Leagues Updated successfully'
				end
			}
		end
	end

	private

	def set_country
		@country = Country.find_by!(slug: params[:country_slug]) if params[:country_slug]
	end
end

app/helpers/leagues_helper.rb
module LeaguesHelper
end

app/views/leagues/_leagues_list.html.erb
<ul class="league-list">
	<% leagues.each do |league| %>
		<li class="league">
			<%= link_to league.name, country_league_path(league.country.slug, league.slug) %>
		</li>
	<% end %>
</ul>

app/views/leagues/index.html.erb
<h1>Leagues#index</h1>

<%=
	button_to "Refresh",
	refresh_country_leagues_path,
	remote: true,
	method: :get
%>

<div id="leagues-container">
	<div id="leagues_list">
		<%= render partial: 'leagues_list', locals: { leagues: @leagues } %>
	</div>
</div>

app/views/leagues/refresh.js.erb
$("#leagues-container").html("<%= j render partial: 'leagues_list', locals: { leagues: @leagues } %>");

app/views/leagues/show.html.erb
<h2>Information</h2>

<h1><%= @league.name %></h1>
<p>Type: <%= @league.league_type %></p>
<%= image_tag @league.logo if @league.logo.present? %>

<p>Name: <%= @league.country.name %></p>
<p>Code: <%= @league.country.code %></p>
<% if @league.country.flag.present? %>
	<p>Flag: <%= image_tag @league.country.flag %></p>
<% end %>

<h2>Seasons for <%= @league.name %></h2>
<%= button_to 'refresh seasons', refresh_country_league_seasons_path(@league.country.slug, @league.id), method: :get, remote: true %>

<%= render partial: 'seasons/seasons_list', locals: { seasons: @league.seasons.order(year: :desc) } %>