config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'countries#index'

	resources :countries, param: :slug, path: '', only: [:index, :show] do
		collection do
			get 'refresh'
		end

		resources :leagues, param: :slug, path: '', only: [:index, :show] do
			collection do
				get 'refresh'
			end

			resources :seasons, param: :slug, path: '', only: [:index, :show] do
				collection do
					get 'refresh'
				end

				resources :fixtures, param: :slug, only: [:index, :show] do
					collection do
						get 'refresh'
					end
				end
			end

			resources :teams, only: [:index, :show] do
				collection do
					get 'refresh'
				end
			end
		end
	end

	#
	#resources :leagues, only: [:index, :show] do
	#	collection do
	#		get 'refresh'
	#	end
	#end

	resources :venues, param: :slug, only: [:index, :show] do
	  collection do
	    get 'refresh'
    end
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
end

app/models/country.rb
class Country < ApplicationRecord
	include Sluggable

	validates :name, presence: true
	validates :slug, uniqueness: true

	has_many :leagues

	def self.fetch_and_update_from_api
		api_client = ApiClient.new
		remote_countries = api_client.fetch('countries')

		remote_countries.each do |remote_country|
			create_or_update(remote_country)
		end
	end

	def self.create_or_update(country_data)
		normalized_name = normalize_name(country_data['name'])
		slug = normalized_name.parameterize
		country = Country.find_or_initialize_by(slug: slug)

		if country.new_record?
			puts "Create country"
			country.assign_attributes(
				name: country_data['name'],
				code: country_data['code'],
				flag: country_data['flag'],
				slug: slug
			)
		else
			puts "Update country"
			country.assign_attributes(
				flag: country_data['flag']
			)
		end

		country.save!
		country

	end

	private

	def country_updated?(remote_country)
		flag != remote_country['flag']
	end

	def self.normalize_name(name)
		name.downcase.gsub(/[^a-z]/, '-')
	end

end

app/controllers/countries_controller.rb
class CountriesController < ApplicationController
	def index
		@countries = Country.all
	end

	def show
		@country = Country.find_by!(slug: params[:slug])
		@leagues = @country.leagues
	end

	def refresh
		Country.fetch_and_update_from_api

		@countries = Country.all
		respond_to do |format|
			format.html {
				render partial: 'countries_list', locals: {
					countries: @countries
				}
			}
		end
	end
end

app/helpers/countries_helper.rb
module CountriesHelper
end

app/views/countries/_countries_list.html.erb
<ul>
	<% countries.each do |country| %>
		<li>
			<%= link_to country.name, country_path(country.slug) %>
		</li>
	<% end %>
</ul>

app/views/countries/index.html.erb
<h1>Countries</h1>
<div id="countries_list">
	<%= render partial: 'countries_list', locals: { countries: @countries } %>
</div>

<%=
	button_to "Refresh",
	refresh_countries_path,
	remote: true,
	method: :get
%>

app/views/countries/show.html.erb
<h1><%= @country.name %></h1>

<div id="leagues-container">

	<%= link_to 'Refresh Leagues', refresh_country_leagues_path(@country.slug), remote: true, method: :get %>

	<%= render partial: 'leagues/leagues_list', locals: { leagues: @country.leagues } %>
</div>